# generated by datamodel-codegen:
#   filename:  assets.ledger.key.json

from __future__ import annotations

from pydantic import BaseModel


class AssetsLedgerKey(BaseModel):
    address: str
    nat: str
